### PR TITLE
Homepage 2

### PR DESCRIPTION
**Pull request by jduss4**
Translates figma design into prototype homepage

Preview:  https://federalist-35400506-693f-4f4d-815c-e4fb7841233f.app.cloud.gov/preview/18f/gsa-small-business-experience/homepage-2/

High priorities:

- [x] hook up opportunity explorer link
- [x] video links pushing content unexpectedly
- [x] video responsive with grid
- [x] add PDF for market research #71 
- [x] hover panel nav should look clickable (they are buttons, booo)
- [x] text of panels should be grey if not active
- [x] panels when hovered: change text to black, bar to light blue

If there's time before usability tests:

- [x] disable state dropdown
- [x] add tablet breaks for different grids, particularly 1 2 3 section
- [x] h3 headers on the headers in the tabs: "Getting on Schedule", "Open Market Opportunities, and "Joint Venture", "Partnerships" and "Subcontracting"
- [x] h4 headers make look like h3 for the panels
- [x] center circles
- ~change background grey and then retry usa-links class for blue and WCAG AAA~
- [x] make opportunity explorer middle page button 80% wide, move to left
- [x] ways of working header remove some of the margins / padding

### CODE REVIEW

**Comment by janelx** [comment]
- [ ] Opportunity Explorer - remove question: “Will all your sales be less than $10K per purchase?”
- [ ] Got no results for Programs instead of MAS with warnings. Selection to recreate:
1. Transportation & logistic services
2. Women owned small business
3. Yes
4. Yes
- [ ] Logo link is giving 404 > Can link to prototype homepage
- [ ] There was some text updated since speaking with FMP and my Crit group. It’s in Figma. 
- [ ] Spacing before and below headers are very wonky - ex.: “Before submitting an offer you’ll need” it should same row as the video
- [ ] Add video on opportunity explorer: https://www.youtube.com/watch?v=dhwAgQqZigs

**Comment by janelx** [comment]
@jduss4 I just realized if we change the question "Are you interested in contracts less than $10K?" an alert doesn't need to be triggered for "yes" or "no".

**Comment by jduss4** [comment]
Was the "Before submitting" header the only one that stuck out to you?  Out of the box all the headers in USWDS come with a considerable margin which looks okay normally but doesn't work so well when they're in the grid against something without the margin.  The only other one that looks a little funky to me is the "Vendor case studies" header

**Comment by jduss4** [comment]
I think I hit all the show stoppers!  https://federalist-35400506-693f-4f4d-815c-e4fb7841233f.app.cloud.gov/preview/18f/gsa-small-business-experience/homepage-2/  🥳 

I will start new branches for adding in fake data, but for now I want to make sure all the above are crossed off!

I didn't change anything on the results page for now, but it would be pretty easy to remove the "MAS is for 10K+" info alert if we decide that doesn't need to be displayed.  However, if that doesn't display then functionally I think that question has no affect on any of the results, so perhaps we could drop it entirely in that case.

**Comment by janelx** [comment]
@jduss4 If it's easy to drop the $10K question then I think we should drop it. I'll update content to include $10K in the description (MAS or subcontracting and open market). 

Not necessary for testing:
Add download for Market Research Guide on explorer results (I forgot)
Clean up spacing

**Comment by jduss4** [comment]
I am going to merge and deploy this for now, then see if I can get the $10K question dropped before the first session!

**Comment by janelx** [comment]
Minor and not a priority, but I just noticed "real estate" is missing from industry list.

**Pull request merged**
